Update doctor's comments on formula
vpn-kill-switch/homebrew-killswitch pull request #3
Opened 2019-10-05 08:46 UTC by javatarz

Will help #20 when this repo gets more stars.

2019-10-06 12:33 UTC, nbari requested changes

2019-10-06 12:33 UTC, nbari commented on killswitch.rb
> +class VpnKillSwitch < Formula
Could we keep the name `Killswitch`

2019-10-07 03:51 UTC, javatarz commented on killswitch.rb
> +class VpnKillSwitch < Formula
Had renamed when I built the homebrew formula on my local to pass the doctor test.

Renamed it to `Killswitch` again.

2019-10-07 06:17 UTC, nbari commented on killswitch.rb
> +class VpnKillSwitch < Formula
What is the "doctor test"?

2019-10-07 06:18 UTC, merged

2019-10-07 06:18 UTC, nbari commented
@javatarz many thanks 👍

2019-10-07 12:46 UTC, javatarz commented on killswitch.rb
> +class VpnKillSwitch < Formula
I meant `brew doctor` from [their contributing.md](https://github.com/Homebrew/brew/blob/master/CONTRIBUTING.md)